# Controllers ------------------------------------------------
head_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - HeadYaw
    - HeadPitch

left_arm_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - LShoulderPitch
    - LShoulderRoll
    - LElbowYaw
    - LElbowRoll

right_arm_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - RShoulderPitch
    - RShoulderRoll
    - RElbowYaw
    - RElbowRoll

left_hand_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - LWristYaw
    - LHand

right_hand_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - RWristYaw
    - RHand

torso_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - HipRoll
    - HipPitch
    - KneePitch



